### ISSUE TITLE
Add On Feature Packages: Help Wanted

### ISSUE THREAD

**Issue by aldeed** [Meteor-Community-Packages/meteor-autoform#438]
People often propose great ideas for features, but they're easy to implement as add-on packages and they're not universal enough to include in the core autoform package. This issue is to track those ideas and propose new ones. If you are going to create a package or already have, post a comment so everyone knows. If you have other ideas, submit a new issue, and I'll close it and list it here if it should be a separate package.
- [ ] custom theme template for afFormGroup that includes help text (#336)
- [ ] json-schema adapter (#258) (will require some core changes, but should be a separate pkg)
- [ ] custom theme template for afFormGroup that includes tooltips (#257)
- [ ] x-editable theme template/input types (#88)
- [ ] custom input type for masking (#406)
- [x] custom input type for datetime picker - https://atmospherejs.com/aldeed/autoform-bs-datetimepicker or https://atmospherejs.com/notorii/autoform-datetimepicker
- [ ] custom input type for color picking
- [ ] custom form group template for #432
- [x] custom input type for Froala (#525) - https://atmospherejs.com/donchess/autoform-froala
- [ ] custom input type for CKEditor (#488)
- [ ] custom input type for TinyMCE (#488)
- [ ] Polymer paper / material design theme (#463)
- [ ] a lightweight add-on package that loops through the window.ParsleyConfig.i18n object and registers all the messages defined there as SimpleSchema messages (#578)
- [ ] custom input type for multiple input range sliders such as http://refreshless.com/nouislider/ (#723)
- [ ] captcha input type (#1260)

**Comment by brylie** [comment]
How would I start working on #336? Is there a basic template that I can clone?

**Comment by aldeed** [comment]
@brylie, if you're doing it for bootstrap, you can copy the [bootstrap template and helpers](https://github.com/aldeed/meteor-autoform/tree/devel/templates/bootstrap3/components/afFormGroup), change the part of the template name after the underscore, add any additional markup and helpers you need, and that should be it.

**Comment by rwatts3** [comment]
has this been implemented yet ?

**Comment by rwatts3** [comment]
Has anyone implemented tool tips yet ?

**Comment by Maqhosha** [comment]
has anyone added the captcha field type to autoform? if anyone did please help my form does submit even if i didn’t fill the captcha values.
thank you

**Comment by boredland** [comment]
@brylie did you work in #336?

**Comment by juliomac** [comment]
Has anyone implemented tooltip ?
